"""Convert backend snapshots into JSON-serialisable dicts for the browser.

The WebSocket broadcaster ships the output of :func:`snapshot_to_json`
verbatim, and the clientside callbacks in ``dashboard/callbacks.py``
expect exactly this shape. Keep the keys stable and add new ones rather
than rename — the front end has no schema version handling beyond the
``version`` monotonic counter at the top level.

Numeric values that may be ``None`` (warmup) are kept as ``None`` rather
than ``NaN`` so the JS side gets a plain ``null`` and can render "n/a".
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Final

import config

_log = logging.getLogger(__name__)

# 16-year offline OOS baseline, generated by scripts/_generate_oos_baseline.py
# and shipped with the project. Loaded once on first call so the dashboard
# pays the file-read cost at most once per process. An absent / malformed
# file degrades to an empty payload — the front end then simply hides the
# "16y reference" line.
_OOS_BASELINE_CACHE: dict[str, Any] | None = None


def load_oos_baseline() -> dict[str, Any]:
    """Read and cache the offline OOS-baseline JSON (idempotent)."""
    global _OOS_BASELINE_CACHE
    if _OOS_BASELINE_CACHE is not None:
        return _OOS_BASELINE_CACHE
    path = Path(__file__).resolve().parent.parent / "data" / "oos_baseline.json"
    if not path.exists():
        _log.info("oos_baseline.json missing at %s — feature degraded", path)
        _OOS_BASELINE_CACHE = {}
        return _OOS_BASELINE_CACHE
    try:
        _OOS_BASELINE_CACHE = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        _log.warning("oos_baseline.json unreadable (%s) — feature degraded", exc)
        _OOS_BASELINE_CACHE = {}
    return _OOS_BASELINE_CACHE
from analyzer.account_monitor import PerformanceSnapshot, RangeStats, SymbolStats
from analyzer.calendar_feed import CalendarEvent, CalendarSnapshot
from analyzer.confluence import ConfluenceCluster
from analyzer.dws_smt import DwsSmtResult
from analyzer.indicator_engine import (
    AnalysisSnapshot,
    ChartBars,
    SymbolIndicators,
    TimeframeIndicators,
)
from analyzer.signal_validator import (
    RegimeStats,
    SubPeriodStats,
    ValidationCore,
    ValidationSnapshot,
    ValidationStats,
)
from analyzer.macro_feed import (
    MacroEmployment,
    MacroPairBias,
    MacroRate,
    MacroSnapshot,
    RealYieldSnapshot,
)
from analyzer.mt5_connector import AccountSnapshot, Tick
from analyzer.position_sizing import recommended_lot
from analyzer.price_action import PriceActionEvent
from analyzer.state import (
    ConnectionStatus,
    LatestState,
    PriceSnapshot,
    StructuresSnapshot,
)
from analyzer.structure_types import StructureLevel


def _opt_float(v: float | None) -> float | None:
    """Pass through floats but coerce NaN and Inf to None for valid JSON.

    MT5 emits ``Inf`` for ``margin_level`` whenever margin is zero (no open
    positions), and ``json.dumps`` raises ``ValueError`` on Inf — without
    this coercion every WS client disconnects on flat accounts.
    """
    if v is None:
        return None
    fv = float(v)
    if fv != fv or fv == float("inf") or fv == float("-inf"):
        return None
    return fv


def serialize_tick(t: Tick) -> dict[str, Any]:
    return {
        "symbol": t.symbol,
        "bid": _opt_float(t.bid),
        "ask": _opt_float(t.ask),
        "last": _opt_float(t.last),
        "time_msc": t.time_msc,
    }


def serialize_price(p: PriceSnapshot | None) -> dict[str, Any] | None:
    if p is None:
        return None
    return {
        "generated_at": p.generated_at,
        "ticks": {base: serialize_tick(t) for base, t in p.ticks.items()},
    }


def serialize_timeframe(tf: TimeframeIndicators) -> dict[str, Any]:
    return {
        "label": tf.label,
        "last_close": _opt_float(tf.last_close),
        "ema": _opt_float(tf.ema),
        "ema_period": tf.ema_period,
        "above_ema": tf.above_ema,
        "rsi": _opt_float(tf.rsi),
        "atr": _opt_float(tf.atr),
        "adx": _opt_float(tf.adx),
        "di_plus": _opt_float(tf.di_plus),
        "di_minus": _opt_float(tf.di_minus),
        "bar_time": tf.bar_time.isoformat() if tf.bar_time is not None else None,
    }


def serialize_chart(c: ChartBars | None) -> dict[str, Any] | None:
    if c is None:
        return None
    return {
        "ohlc_h4": [[float(o), float(h), float(l), float(cl)]
                    for (o, h, l, cl) in c.ohlc_h4],
        "closes_m15": [float(v) for v in c.closes_m15],
        "ema_h4": _opt_float(c.ema_h4),
    }


def serialize_dws_smt(d: DwsSmtResult | None) -> dict[str, Any] | None:
    """Serialise the DWS-SMT histogram as compact column arrays.

    Each base window ships parallel arrays: ``t`` = epoch-ms bar times,
    ``c`` = per-bar ``[row, ...]`` colour indices (0 up / 1 down / 2 flat),
    ``g`` = per-bar trigger ("BUY"/"SELL"/"EXIT") or ``None``, ``bias`` = the
    per-bar composite BIAS score (-10..+10, judged at that bar's own time),
    ``fn`` = per-bar ``[row, ...]`` signed distance-to-flip in [-1, 1]
    (display-only flip-proximity gradient).
    ``trades`` lists paired entry→exit trades — ``i`` entry bar, ``d`` direction
    (+1/-1), ``p`` signed price points, ``m`` max adverse excursion, ``o`` open.
    """
    if d is None:
        return None
    return {
        "by_base": {
            base: {
                "base_tf": w.base_tf,
                "rows": list(w.rows),
                "t": w.times_ms.tolist(),
                "c": w.colors.tolist(),
                "g": list(w.triggers),
                "bias": [round(float(x), 2) for x in w.bias],
                "fn": [[round(float(v), 3) for v in row] for row in w.flip_norm],
                "trades": [
                    {"i": tr.entry_idx, "d": tr.direction,
                     "p": round(tr.points, 5), "m": round(tr.mae, 5),
                     "o": tr.is_open}
                    for tr in w.trades
                ],
            }
            for base, w in d.by_base.items()
        },
    }


def serialize_symbol(sym: SymbolIndicators) -> dict[str, Any]:
    return {
        "base": sym.base,
        "broker_name": sym.broker_name,
        "by_tf": {label: serialize_timeframe(tf) for label, tf in sym.by_tf.items()},
        "chart": serialize_chart(sym.chart),
        "dws": serialize_dws_smt(sym.dws),
    }


def serialize_analysis(a: AnalysisSnapshot | None) -> dict[str, Any] | None:
    if a is None:
        return None
    return {
        "generated_at": a.generated_at.isoformat(),
        "compute_ms": float(a.compute_ms),
        "by_symbol": {base: serialize_symbol(s) for base, s in a.by_symbol.items()},
    }


def serialize_account(acc: AccountSnapshot | None) -> dict[str, Any] | None:
    if acc is None:
        return None
    return {
        "login": acc.login,
        "server": acc.server,
        "company": acc.company,
        "currency": acc.currency,
        "balance": _opt_float(acc.balance),
        "equity": _opt_float(acc.equity),
        "profit": _opt_float(acc.profit),
        "margin": _opt_float(acc.margin),
        "margin_free": _opt_float(acc.margin_free),
        "margin_level": _opt_float(acc.margin_level),
        "leverage": int(acc.leverage),
        # Both account + terminal permit live trading — the order panel enables
        # its BUY/SELL/close buttons only when this is true.
        "trade_allowed": bool(getattr(acc, "trade_allowed", False)),
        # Recommended trade size from the validated fixed-fractional lot ladder
        # (single source of truth in analyzer.position_sizing). Sized off the
        # settled BALANCE (not equity) so the recommendation does not wobble
        # with open floating P/L. lot_rule carries the params so the UI can
        # render the rule subtitle without hard-coding.
        "recommended_lot": recommended_lot(acc.balance),
        "lot_rule": {
            "base": config.LOT_BASE,
            "step": config.LOT_EQUITY_STEP,
            "max": config.LOT_MAX,
        },
        "positions": [
            {
                "ticket": p.ticket,
                "symbol": p.symbol,
                "type": p.type,
                "volume": _opt_float(p.volume),
                "price_open": _opt_float(p.price_open),
                "price_current": _opt_float(p.price_current),
                "sl": _opt_float(p.sl),
                "tp": _opt_float(p.tp),
                "profit": _opt_float(p.profit),
                "swap": _opt_float(p.swap),
                "time": int(p.time),
            }
            for p in acc.positions
        ],
    }


def serialize_status(s: ConnectionStatus) -> dict[str, Any]:
    return {
        "connected": bool(s.connected),
        "last_error": s.last_error,
        "last_connect_ts": s.last_connect_ts,
    }


# --------------------------------------------------------------------------- #
# Phase 2: structures / price action / confluence
# --------------------------------------------------------------------------- #

def serialize_level(lv: StructureLevel) -> dict[str, Any]:
    return {
        "name": lv.name,
        "kind": lv.kind.value,
        "category": lv.category,
        "source": lv.source.value,
        "price": _opt_float(lv.price),
        "importance": int(lv.importance),
        "color": lv.color,
        "tf": lv.tf,
        # meta may contain nested datetimes etc.; we coerce known sub-types
        # rather than dumping arbitrary content to avoid silent json errors.
        "meta": _safe_meta(lv.meta),
    }


def serialize_price_action(ev: PriceActionEvent) -> dict[str, Any]:
    return {
        "kind": ev.kind.value,
        "bar_time": ev.bar_time.isoformat() if ev.bar_time is not None else None,
        "bar_index_from_end": int(ev.bar_index_from_end),
        "direction": int(ev.direction),
        "close": _opt_float(ev.close),
        "extreme": _opt_float(ev.extreme),
        "body": _opt_float(ev.body),
        "note": ev.note,
        "meta": _safe_meta(ev.meta),
    }


def serialize_confluence(c: ConfluenceCluster) -> dict[str, Any]:
    return {
        "center": _opt_float(c.center),
        "price_low": _opt_float(c.price_low),
        "price_high": _opt_float(c.price_high),
        "width": _opt_float(c.width),
        "distance": _opt_float(c.distance),
        "score": int(c.score),
        "importance_label": c.importance_label,
        "level_names": [lv.name for lv in c.levels],
        "level_categories": [lv.category for lv in c.levels],
        "level_sources": [lv.source.value for lv in c.levels],
    }


def serialize_structures(s: StructuresSnapshot | None) -> dict[str, Any] | None:
    if s is None:
        return None
    # The flattened wire shape keeps the existing per-domain keys at the top
    # level for the front end — the only change is that the backend now
    # builds them in a single loop from one source dict.
    by_sym = s.by_symbol
    return {
        "generated_at": float(s.generated_at),
        "levels_by_symbol": {
            base: [serialize_level(lv) for lv in sym.levels]
            for base, sym in by_sym.items()
        },
        "price_action_by_symbol": {
            base: [serialize_price_action(ev) for ev in sym.price_action]
            for base, sym in by_sym.items()
        },
        "confluences_by_symbol": {
            base: [serialize_confluence(c) for c in sym.confluences]
            for base, sym in by_sym.items()
        },
    }


# --------------------------------------------------------------------------- #
# Phase 3: performance
# --------------------------------------------------------------------------- #

def serialize_symbol_stats(s: SymbolStats) -> dict[str, Any]:
    return {
        "symbol": s.symbol,
        "trade_count": int(s.trade_count),
        "win_count": int(s.win_count),
        "net_profit": _opt_float(s.net_profit),
        "win_rate": _opt_float(s.win_rate),
    }


def serialize_range_stats(r: RangeStats) -> dict[str, Any]:
    return {
        "range_label": r.range_label,
        "trade_count": int(r.trade_count),
        "win_count": int(r.win_count),
        "loss_count": int(r.loss_count),
        "win_rate": _opt_float(r.win_rate),
        "profit_factor": _opt_float(r.profit_factor),
        "max_drawdown_abs": _opt_float(r.max_drawdown_abs),
        "max_drawdown_pct": _opt_float(r.max_drawdown_pct),
        "avg_win": _opt_float(r.avg_win),
        "avg_loss": _opt_float(r.avg_loss),
        "risk_reward": _opt_float(r.risk_reward),
        "gross_profit": _opt_float(r.gross_profit),
        "gross_loss": _opt_float(r.gross_loss),
        "net_profit": _opt_float(r.net_profit),
        "by_symbol": {sym: serialize_symbol_stats(ss)
                      for sym, ss in r.by_symbol.items()},
        "by_hour_jst": {str(h): _opt_float(v) for h, v in r.by_hour_jst.items()},
    }


def serialize_performance(s: PerformanceSnapshot | None) -> dict[str, Any] | None:
    if s is None:
        return None
    return {
        "generated_at": float(s.generated_at),
        "compute_ms": float(s.compute_ms),
        "fetched_from_ts": float(s.fetched_from_ts),
        "fetched_to_ts": float(s.fetched_to_ts),
        "open_trade_count": int(s.open_trade_count),
        "today_realised_pnl": _opt_float(s.today_realised_pnl),
        "today_floating_pnl": _opt_float(s.today_floating_pnl),
        "today_total_pnl": _opt_float(s.today_total_pnl),
        "ranges": [r.label for r in config.HISTORY_RANGES],
        "default_range": config.HISTORY_DEFAULT_RANGE,
        "by_range": {label: serialize_range_stats(rs)
                     for label, rs in s.by_range.items()},
    }


# Central-bank rate-decision label keyed by the event's currency. The English
# title still drives the upstream keyword filter; this only localises display.
_JP_RATE_BY_CCY: Final[dict[str, str]] = {
    "USD": "FOMC 政策金利発表",
    "EUR": "ECB 政策金利発表",
    "GBP": "BoE 政策金利発表",
    "JPY": "日銀 金融政策決定会合",
    "AUD": "RBA 政策金利発表",
}
_JP_RATE_KEYWORDS: Final[tuple[str, ...]] = (
    "fomc", "ecb", "boe", "boj", "rba", "governing council", "mpc",
    "bank rate", "cash rate", "rate decision", "rate statement",
    "monetary policy", "interest rate", "federal funds", "refinancing",
    "policy rate",
)


def _jp_calendar_title(title: str, ccy: str) -> str:
    """Localise a high-impact event title to Japanese for display.

    Employment releases map by type; rate decisions map to the right central
    bank via the event currency. Anything unrecognised falls back to the
    original title so nothing is ever dropped."""
    t = title.lower()
    # ADP is "ADP Non-Farm Employment Change" — a PRIVATE payroll estimate, NOT
    # the official BLS NFP. Match it FIRST so it doesn't collapse into "NFP".
    if "adp" in t:
        return "ADP雇用統計"
    if any(k in t for k in ("non-farm", "nonfarm", "payroll")):
        return "米雇用統計 (NFP)"
    if any(k in t for k in ("unemployment", "jobless", "claimant")):
        return "失業率"
    if "press conference" in t:
        return "中銀総裁会見"
    if any(k in t for k in _JP_RATE_KEYWORDS):
        return _JP_RATE_BY_CCY.get(ccy, "政策金利発表")
    return title


# Category chip keys — derived from the ENGLISH title so the badge survives
# title localisation. Kept in sync with the front-end fallback.
_CAT_EMP_KEYWORDS: Final[tuple[str, ...]] = (
    "payroll", "nonfarm", "non-farm", "employment", "unemploy", "jobless",
    "hourly earnings", "earnings index", "claimant count", "jolts", "adp",
)
_CAT_RATE_KEYWORDS: Final[tuple[str, ...]] = (
    "fomc", "federal funds rate", "bank rate", "cash rate", "policy rate",
    "refinanc", "rate statement", "rate decision", "monetary policy",
    "interest rate", "press conference",
)


def _calendar_category(title: str) -> str:
    """Classify an event as employment / rate / other from its English title."""
    t = title.lower()
    if any(k in t for k in _CAT_EMP_KEYWORDS):
        return "emp"
    if any(k in t for k in _CAT_RATE_KEYWORDS):
        return "rate"
    return "oth"


def serialize_calendar_event(e: CalendarEvent) -> dict[str, Any]:
    # Classify from the original English title, THEN localise the display text.
    return {
        "release_ts": float(e.release_ts),
        "currency": e.currency,
        "title": _jp_calendar_title(e.title, e.currency),
        "category": _calendar_category(e.title),
        "impact": e.impact,
        "forecast": e.forecast,
        "previous": e.previous,
        "actual": e.actual,
        "source": e.source,
        "source_url": getattr(e, "source_url", ""),
    }


def serialize_calendar(s: CalendarSnapshot | None) -> dict[str, Any] | None:
    if s is None:
        return None
    return {
        "generated_at": float(s.generated_at),
        # fetched_at == 0 means "never fetched"; emit null so the front-end
        # does not render epoch 1970.
        "fetched_at": float(s.fetched_at) if s.fetched_at > 0 else None,
        "source": s.source,
        "last_error": s.last_error,
        "consecutive_failures": int(s.consecutive_failures),
        "warning_window_sec": int(config.CALENDAR_WARNING_WINDOW_SEC),
        "display_count": int(config.CALENDAR_DISPLAY_COUNT),
        "events": [serialize_calendar_event(e) for e in s.events],
    }


# --------------------------------------------------------------------------- #
# Signal validation layer (precision-optimization spec, Section A)
# --------------------------------------------------------------------------- #

def _serialize_sub_period(s: SubPeriodStats) -> dict[str, Any]:
    return {
        "win_rate": _opt_float(s.win_rate),
        "expectancy": _opt_float(s.expectancy),
        "n_trades": int(s.n_trades),
    }


def _serialize_regime(s: RegimeStats) -> dict[str, Any]:
    return {
        "win_rate": _opt_float(s.win_rate),
        "expectancy": _opt_float(s.expectancy),
        "n_trades": int(s.n_trades),
    }


def serialize_validation_core(c: ValidationCore) -> dict[str, Any]:
    """Serialise one :class:`ValidationCore`.

    ``profit_factor`` may be ``inf`` (no losing trades); ``_opt_float`` maps
    that to ``null`` so ``json.dumps`` never raises.
    """
    return {
        "n_trades": int(c.n_trades),
        "win_rate": _opt_float(c.win_rate),
        "ci_low": _opt_float(c.ci_low),
        "ci_high": _opt_float(c.ci_high),
        "profit_factor": _opt_float(c.profit_factor),
        "expectancy": _opt_float(c.expectancy),
        "max_drawdown": _opt_float(c.max_drawdown),
        "avg_mae": _opt_float(c.avg_mae),
        "thirds": [_serialize_sub_period(t) for t in c.thirds],
        "regime_trend": _serialize_regime(c.regime_trend),
        "regime_range": _serialize_regime(c.regime_range),
        "tier": c.tier,
        # Live broker recent-trigger history (newest first): t=epoch ms,
        # d=±1 direction, p=net points after spread, o=open (still-running)
        # trigger — p is floating P/L, excluded from realised stats.
        "recent_triggers": [
            {"t": int(r.entry_ms), "d": int(r.direction),
             "p": round(r.net_pts, 1), "o": bool(r.is_open)}
            for r in c.recent_triggers
        ],
    }


def serialize_validation_stats(s: ValidationStats) -> dict[str, Any]:
    return {
        "symbol": s.symbol,
        "base_tf": s.base_tf,
        "raw": serialize_validation_core(s.raw),
        "macro_filtered": serialize_validation_core(s.macro_filtered),
    }


def serialize_validation(s: ValidationSnapshot | None) -> dict[str, Any] | None:
    """Serialise the whole validation snapshot for the WebSocket payload."""
    if s is None:
        return None
    return {
        "generated_at": float(s.generated_at),
        "compute_ms": float(s.compute_ms),
        "min_trades": int(config.VALIDATION_MIN_TRADES),
        "by_symbol": {
            sym: {tf: serialize_validation_stats(st) for tf, st in per_tf.items()}
            for sym, per_tf in s.by_symbol.items()
        },
    }


# --------------------------------------------------------------------------- #
# Macro / rate-differential layer (precision-optimization spec, Section B)
# --------------------------------------------------------------------------- #

def _serialize_macro_rate(r: MacroRate) -> dict[str, Any]:
    return {
        "currency": r.currency,
        "rate": _opt_float(r.rate),
        "as_of": r.as_of,
        "prev_rate": _opt_float(r.prev_rate),
        "source": r.source,
        "stale": bool(r.stale),
    }


def _serialize_macro_pair(b: MacroPairBias) -> dict[str, Any]:
    return {
        "pair": b.pair,
        "base_ccy": b.base_ccy,
        "quote_ccy": b.quote_ccy,
        "differential": _opt_float(b.differential),
        "macro_dir": int(b.macro_dir),
        "label": b.label,
    }


def _serialize_macro_employment(e: MacroEmployment | None) -> dict[str, Any] | None:
    if e is None:
        return None
    return {
        "nonfarm_change": _opt_float(e.nonfarm_change),
        "unemployment_rate": _opt_float(e.unemployment_rate),
        "as_of": e.as_of,
        "prev_nonfarm_change": _opt_float(e.prev_nonfarm_change),
        "source": e.source,
        "stale": bool(getattr(e, "stale", False)),
    }


def serialize_macro(s: MacroSnapshot | None) -> dict[str, Any] | None:
    """Serialise the macro snapshot for the WebSocket payload."""
    if s is None:
        return None
    return {
        "generated_at": float(s.generated_at),
        "fetched_at": float(s.fetched_at) if s.fetched_at > 0 else None,
        "rates": {ccy: _serialize_macro_rate(r) for ccy, r in s.rates.items()},
        "employment": _serialize_macro_employment(s.employment),
        "by_pair": {p: _serialize_macro_pair(b) for p, b in s.by_pair.items()},
        "last_error": s.last_error,
        "consecutive_failures": int(s.consecutive_failures),
    }


def serialize_real_yield(s: RealYieldSnapshot | None) -> dict[str, Any] | None:
    """Serialise the US 10Y real-yield snapshot for the WebSocket payload."""
    if s is None:
        return None
    return {
        "value": _opt_float(s.value),
        "prev_value": _opt_float(s.prev_value),
        "change_1d": _opt_float(s.change_1d),
        "trend_5d": _opt_float(s.trend_5d),
        "gold_dir": int(s.gold_dir),
        "as_of": s.as_of,
        "stale": bool(s.stale),
        "generated_at": float(s.generated_at),
    }


# --------------------------------------------------------------------------- #


def _safe_meta(
    meta: dict[str, Any], _visited: set[int] | None = None
) -> dict[str, Any]:
    """Best-effort JSON-safe coercion for level/PA meta dicts.

    A ``_visited`` set guards against self-referential or cyclic dicts; the
    EA parser is defensive but a hand-crafted ``lines_*.json`` could in
    theory smuggle one in, and infinite recursion here would crash the WS
    broadcaster for every connected client.
    """
    if _visited is None:
        _visited = set()
    out: dict[str, Any] = {}
    for k, v in meta.items():
        if v is None or isinstance(v, (bool, int, str)):
            out[k] = v
        elif isinstance(v, float):
            out[k] = _opt_float(v)
        elif isinstance(v, (list, tuple)):
            out[k] = list(v)  # ISO-time strings & numbers pass through
        elif isinstance(v, dict):
            if id(v) in _visited:
                out[k] = "<cycle>"
                continue
            _visited.add(id(v))
            out[k] = _safe_meta(v, _visited)
            _visited.discard(id(v))
        else:
            out[k] = str(v)
    return out


def snapshot_to_json(state: LatestState, include_baseline: bool = True) -> dict[str, Any]:
    """Render the entire :class:`LatestState` into a flat JSON-ready dict.

    *include_baseline* controls whether the static 2 MB ``oos_baseline`` is
    embedded. It never changes for the process lifetime, so the broadcaster
    ships it only in the FIRST full snapshot per connection and passes
    ``include_baseline=False`` on every recurring full — the client caches the
    first copy. Default ``True`` keeps the function self-contained for tests
    and the smoke verifier.
    """
    snap = state.snapshot()
    out: dict[str, Any] = {
        "version": int(snap["version"]),  # type: ignore[arg-type]
        "ts": float(snap["ts"]),  # type: ignore[arg-type]
        "status": serialize_status(snap["status"]),  # type: ignore[arg-type]
        "price": serialize_price(snap["price"]),  # type: ignore[arg-type]
        "analysis": serialize_analysis(snap["analysis"]),  # type: ignore[arg-type]
        "account": serialize_account(snap["account"]),  # type: ignore[arg-type]
        "structures": serialize_structures(snap["structures"]),  # type: ignore[arg-type]
        "performance": serialize_performance(snap["performance"]),  # type: ignore[arg-type]
        "calendar": serialize_calendar(snap["calendar"]),  # type: ignore[arg-type]
        "validation": serialize_validation(snap["validation"]),  # type: ignore[arg-type]
        "macro": serialize_macro(snap["macro"]),  # type: ignore[arg-type]
        "real_yield": serialize_real_yield(snap["real_yield"]),  # type: ignore[arg-type]
        "validation_history": snap.get("validation_history") or {},
        # Persistent live trigger history (per broker): complete year-bucketed
        # record accumulated on disk, so the dashboard shows every live year in
        # full — not just the broker's sliding window. ``server`` names the
        # broker the record belongs to (shown in the UI).
        "live_history": {
            "server": snap.get("live_trigger_server"),
            "by_symbol": snap.get("live_trigger_history") or {},
        },
        "symbol_order": [s.base for s in config.SYMBOLS],
        "symbol_meta": {
            s.base: {
                "display_size": s.display_size,
                "round_step": s.round_step,
                # Pips-conversion meta (config-driven, connection-independent):
                # oos_point = the frozen baseline's price/point; pip_price = the
                # market pip in price units. Lets the frontend render net P/L in
                # PIPS for BOTH the 16Y baseline and the live feed consistently.
                **(
                    {"oos_point": config.OOS_BASELINE_POINT[s.base],
                     "pip_price": config.PIP_PRICE[s.base]}
                    if s.base in config.OOS_BASELINE_POINT
                    and s.base in config.PIP_PRICE else {}
                ),
                # Broker-provided numeric meta (filled in once at startup) —
                # used by the frontend to compute pips/spread in broker units
                # instead of guessing from price magnitude.
                **(snap.get("broker_meta", {}) or {}).get(s.base, {}),
            }
            for s in config.SYMBOLS
        },
    }
    # Static 16-y OOS baseline: ~2 MB and constant for the whole process. Ship
    # it only on the first full snapshot per connection (the client caches it),
    # so it is not re-serialised + re-sent on every analysis tick + heartbeat.
    if include_baseline:
        out["oos_baseline"] = load_oos_baseline()
    return out


def snapshot_light(state: LatestState) -> dict[str, Any]:
    """A price-only update: status / price / account, no heavy analysis blocks.

    Sent at the 2 Hz price cadence so the ~169 KB analysis payload is not
    re-shipped every tick. ``partial: True`` tells the client to MERGE this
    into the snapshot it already holds rather than replace it.

    Uses :meth:`LatestState.light_snapshot` (not the full ``snapshot``) so the
    ever-growing live-trigger history is not deep-copied twice a second for
    fields this payload never includes.
    """
    snap = state.light_snapshot()
    return {
        "partial": True,
        "version": int(snap["version"]),  # type: ignore[arg-type]
        "ts": float(snap["ts"]),  # type: ignore[arg-type]
        "status": serialize_status(snap["status"]),  # type: ignore[arg-type]
        "price": serialize_price(snap["price"]),  # type: ignore[arg-type]
        "account": serialize_account(snap["account"]),  # type: ignore[arg-type]
    }
